### ISSUE TITLE
I want to contribute to torrenttunes

### ISSUE THREAD

**Issue by Legitimate** [tchoulihan/torrenttunes-client#103]
Possibly related to https://github.com/dessalines/torrenttunes-client/issues/101

When launching torrentunes it gets stuck at checking for updates.

This is the output:
```
15:26:28.572 [main] INFO  ROOT - Copying launcher jar to C:\Users\Nesquil/.torrenttunes-client/torrenttunes-launcher.jar ...
> 15:26:28.580 [main] INFO  ROOT - This jar: C:/Users/Nesquil/Downloads/torrenttunes-launcher.jar Launcher Jar: C:\Users\Nesquil/.torrenttunes-client/torrenttunes-launcher.jar
> 15:26:28.608 [main] INFO  c.t.launcher.tools.Updater - Checking for update...
```

I want to become a contributor for torrenttunes. This is how far along I am:
![image](https://user-images.githubusercontent.com/1203600/43997611-a424fe72-9d9d-11e8-8155-dac23fd22ce8.png)

How do I set up my project so that the declared package matches the expected package?

**Comment by dessalines** [comment]
This is the first interest I've had for this project in years, its been largely abandoned, and needs a central server unfortunately which I don't have running. 

The other reason I abandoned it is because it creates potentially millions of torrents (for each song), which I thought would be good for normalization purposes, but unfortunately the embedded libtorrent client does reach a carrying capacity.

**Comment by Legitimate** [comment]
I want to decentralize the system by using IPFS for the database. I have a domain ready to go also. If you can help me get it going with what you have so far, I would be happy to work on moving it away from being centralized. I plan on having a demo complete by September 9th for a Hackathon. I will give attribution to you for your great work. I was elated to find this project as a starting point for what I want to get done.

Here's an overview of my project: https://devpost.com/software/etherradio-nuaz9q

**Comment by Legitimate** [comment]
Please send me an exported jar of the project so I can import it into a blank project in Eclipse.

**Comment by dessalines** [comment]
https://github.com/dessalines/torrenttunes-client/releases
