### ISSUE TITLE
Performance Issues - High CPU and RAM usage

### ISSUE THREAD

**Issue by tchoulihan** [tchoulihan/torrenttunes-client#11]
Referenced in #9 .

* Need to do profiling.

**Comment by tchoulihan** [comment]
This should improve performance a bit : 739d70d990eb60ebb63d1d943a423ed979d3c10b

**Comment by Clarin98** [comment]
I have the same issue in linux mint 17.2, first memory usage was 60 MB, now is in 140 MB and growing... 
![captura de pantalla de 2015-09-21 17 37 27](https://cloud.githubusercontent.com/assets/14655066/10007103/4dd3b41e-6088-11e5-81a5-95758326befe.png)

**Comment by tchoulihan** [comment]
Profiling is still on my todo list.

**Comment by tchoulihan** [comment]
I added a line to keep the threads down on the web server, and this seemed to fix 99% of the performance problems.
