### ISSUE TITLE
How are Trending Songs/Albums calculated?

### ISSUE THREAD

**Issue by Nutomic** [tchoulihan/torrenttunes-client#14]
They haven't changed at all in the past few days.

**Comment by tchoulihan** [comment]
That's true, right now for simplicities sake, trending just really means popular, sorted by plays desc.

This is a a little far back on my priority list, but I plan on implementing this algorithm to periodically fill extra sql tables that do trending by week, day, month, year, all-time, etc.

http://stackoverflow.com/a/826509/1655478

Its literally just me working on this right now, so I'm a little swamped, but its on the radar.

**Comment by Nutomic** [comment]
Of course, I was mostly being curious.

Another idea would be to sort by most seeded (or give it as an option). Assuming that data is available of course.

**Comment by tchoulihan** [comment]
That's possible too, #_of_seeders is a column in that table as well.

**Comment by tchoulihan** [comment]
I've since come up with a better algorithm for trending.
