### ISSUE TITLE
Magnet links for individual songs and albums

### ISSUE THREAD

**Issue by Clarin98** [tchoulihan/torrenttunes-client#23]
You may create a button with magnet links of every album and every song, and people can download that to support the seeders work...

**Comment by tchoulihan** [comment]
I think I know where to add the magnet links for each song, but albums would be tougher.

There aren't any actual album torrents, only torrents for songs. Maybe theres a way I could create a link to group up a bunch of magnet links, and add them all at once.

**Comment by tchoulihan** [comment]
I'm thinking here that a good way to do artist and album magnet links, would be to serve up a .zip file containing all the individual song torrents for that artist or album. I looked into a few torrents clients ability to handle the multiple magnet URI scheme, and unfortunately most don't support it.

Now I'm debating whether to add individual song magnet links at all, and just only do album or artist-wide zips of song torrents.
