### ISSUE TITLE
/r/torrenttunes based radio station(s)

### ISSUE THREAD

**Issue by tchoulihan** [tchoulihan/torrenttunes-client#25]
Create user-voted radio station(s):
* Add a music-streaming flair that has to be torrenttunes song links. Periodically add songs from that list.
* Don't need to add categories, those are already within the MBID, so I could have category based radio-stations.

**Comment by Nutomic** [comment]
Can you explain this a bit? Where will the playlists be stored? And will it also work without Reddit?

**Comment by tchoulihan** [comment]
Basically have this functionality:
http://radioreddit.com/listen/

I'll basically allow people to submit torrenttunes song links to /r/torrenttunes, under a music-streaming flair. Then have radio buttons(by either all or specific genre) on the site that will periodically poll the subreddit, and add songs to your current play queue.

Its a subreddit-voted radio station.

**Comment by Nutomic** [comment]
Peronally, I think it would be a good idea to be independent from any centralized site. They might for example delete links to pirated content.

But I guess this could also be added later.

**Comment by tchoulihan** [comment]
This is something that will be on the backburner for now.
