### ISSUE TITLE
Client not starting

### ISSUE THREAD

**Issue by Nutomic** [tchoulihan/torrenttunes-client#3]
As I understand, a browser should be opened, but nothing happens. Terminal output:
```
$ ./torrenttunes-launcher.jar 
22:13:52.931 [main] INFO  ROOT - Copying launcher jar to /home/felix/.torrenttunes-client/torrenttunes-launcher.jar ...
22:13:52.941 [main] INFO  com.torrenttunes.launcher.Updater - Checking for update...
22:13:55.748 [main] INFO  com.torrenttunes.launcher.Updater - Installation /home/felix/.torrenttunes-client/src/version Not found.
22:13:55.748 [main] INFO  com.torrenttunes.launcher.Updater - Current Tag #: null
22:13:55.748 [main] INFO  com.torrenttunes.launcher.Updater - Latest Tag #: 0.3.0
22:13:55.748 [main] INFO  com.torrenttunes.launcher.Updater - Update found, Downloading...
22:15:27.228 [main] INFO  com.torrenttunes.launcher.Updater - sleeping for a second...
22:15:27.229 [main] INFO  com.torrenttunes.launcher.Updater - Installing update...
22:15:29.667 [main] INFO  com.torrenttunes.client.tools.Tools - Setting up ~/.torrenttunes-client dirs
22:15:29.679 [main] ERROR com.torrenttunes.client.tools.Tools - file : /home/felix/.torrenttunes-client/src/version doesn't exist.
22:15:29.679 [main] INFO  com.torrenttunes.client.tools.Tools - Copying resources to  ~/.torrenttunes-client dirs
22:15:31.499 [main] INFO  com.torrenttunes.client.tools.Tools - Installing linux shortcuts...
22:15:31.798 [main] INFO  com.torrenttunes.client.tools.Tools - tools.js = /home/felix/.torrenttunes-client/src/web/js/tools.js
22:15:31.880 [main] INFO  c.t.client.db.InitializeTables - Using database located at : /home/felix/.torrenttunes-client/db/db.sqlite
22:15:32.100 [main] INFO  c.t.client.db.InitializeTables - Opened database successfully
22:15:32.310 [main] INFO  c.t.client.db.InitializeTables - Table created successfully
22:15:32.465 [main] INFO  com.torrenttunes.launcher.Updater - Deleted temporary install jar: /home/felix/torrenttunes-client.jar
22:15:33.252 [main] INFO  com.torrenttunes.client.tools.Tools - Home directory already exists
22:15:33.262 [main] INFO  com.torrenttunes.client.tools.Tools - The source directory already exists
22:15:33.262 [main] INFO  com.torrenttunes.client.tools.Tools - tools.js = /home/felix/.torrenttunes-client/src/web/js/tools.js
22:15:33.286 [main] INFO  c.t.client.db.InitializeTables - Using database located at : /home/felix/.torrenttunes-client/db/db.sqlite
22:15:33.288 [main] INFO  c.t.client.db.InitializeTables - DB already exists
22:15:33.531 [main] INFO  com.torrenttunes.client.db.Actions - Storage path = /home/felix/.torrenttunes-client/music
22:15:33.531 [main] INFO  com.torrenttunes.client.db.Actions - Applying libtorrent Settings...
22:15:33.533 [main] INFO  c.t.client.tools.DataSources - Operating system linux
22:15:33.533 [main] INFO  c.t.client.tools.DataSources - Using libtorrent @ /home/felix/.torrenttunes-client/src/lib/x86_64/libjlibtorrent.so
22:15:33.557 [main] INFO  c.t.client.LibtorrentEngine - Starting up libtorrent with version: 1.1.0.0
22:15:33.614 [main] INFO  c.t.client.LibtorrentEngine - Is DHT Running? false
22:15:33.742 [main] INFO  com.torrenttunes.client.tools.Tools - Could not connect to local webservice, retrying in 500ms up to 30 seconds
22:15:35.345 [main] INFO  c.t.client.LibtorrentEngine - Done seeding library, total of 0 torrents shared
22:19:29.623 [qtp930956015-23] ERROR com.torrenttunes.client.tools.Tools - file : /home/felix/.torrenttunes-client/src/web/html/favicon.ico.html doesn't exist.
22:19:29.673 [qtp930956015-22] ERROR com.torrenttunes.client.tools.Tools - file : /home/felix/.torrenttunes-client/src/web/html/favicon.ico.html doesn't exist.
```

Kubuntu 15.04
openjdk version "1.8.0_45-internal"
OpenJDK Runtime Environment (build 1.8.0_45-internal-b14)
OpenJDK 64-Bit Server VM (build 25.45-b02, mixed mode)

**Comment by tchoulihan** [comment]
Hrm, my guess is that for some reason its not playing niceley with your default browser.

Do this to make sure torrenttunes is dead:
`pkill -f torrenttunes`

Then load up your browser **first**. 

And try running the launcher again.

**Comment by Nutomic** [comment]
Ah I forgot, browser is Firefox 40.0.3. I had the browser started first, but tried it again with your instructions and it didn't help.

Can I somehow access the GUI manually in the meantime?

**Comment by tchoulihan** [comment]
Yep, the GUI is a local html file, located at:

`/home/your_user_name/.torrenttunes-client/src/web/html/main.html`

**Comment by Nutomic** [comment]
This worked, although I have to reload the site really fast after starting the jar, or the jar will just shut down.

Also, icons are now missing. It's probably a cache problem (it works in Chromium). Strg + F5 didn't fix it though.

**Comment by tchoulihan** [comment]
The icons are a problem in firefox for me, and I can't figure out how to get them to work without adding a security exception in firefox. 

For some reason, firefox is the only browser that has strict security limitations on local fonts, and so any local application using font-awesome doesn't work, unless you turn off a security feature. I tried to complain in the mozilla forums about this, but was pretty much ignored.

Here's a workaround:
http://stackoverflow.com/a/19817460

**Comment by tchoulihan** [comment]
I might have a fix for this in an upcoming release, I'll make a new issue for it.

**Comment by tchoulihan** [comment]
Can you run this line, and see what default browser your OS has?
`sudo update-alternatives –config x-www-browser`

**Comment by Nutomic** [comment]
They are both set to `/usr/bin/firefox`. Also, Zeronet and Syncthing open the browser correctly, just like `xdg-open som.html`.

**Comment by tchoulihan** [comment]
Ah I finally am figuring out why this isn't working right. Turns out the java Desktop class I'm using [here](https://github.com/tchoulihan/torrenttunes-client/blob/master/src/main/java/com/torrenttunes/client/tools/Tools.java#L684) only works for GNOME/Windows/Mac osx, and wasn't built to support KDE.

I'll use a new version using some info from here:

http://stackoverflow.com/questions/18004150/desktop-api-is-not-supported-on-the-current-platform
