### ISSUE TITLE
Create a repeat button

### ISSUE THREAD

**Issue by Clarin98** [tchoulihan/torrenttunes-client#40]
Could appear near to "next" button, on the left side of the "playlist" button.

**Comment by tchoulihan** [comment]
I'll do this in the next update, it looks really easy to implement:

http://www.schillmania.com/projects/soundmanager2/demo/bar-ui/

**Comment by Clarin98** [comment]
Thanks, and don't forget a random button!

**Comment by tchoulihan** [comment]
For now unfortunately the random/shuffle button is unavailable, because its not built into the framework prototype I'm using above. I can pester the maintainer of that project to consider adding it though.
