### ISSUE TITLE
Torrenttunes - share songs from the command line

### ISSUE THREAD

**Issue by modmar** [tchoulihan/torrenttunes-client#44]
It would be possible run torrenttunes in a server (without desktop environment) and maybe connect  to it by Internet?
I want to share my collection and help to share others songs, but i don´t want another computer on all the day. Thank you

**Comment by tchoulihan** [comment]
What I think you want, is a torrenttunes **command line** interface. So would you basically rsync all your music onto some server, then startup torrenttunes from the command line, and run a command that would share a folder. 

Would that work?

**Comment by modmar** [comment]
Yes, it would work.

**Comment by tchoulihan** [comment]
This is done now, here's how to do it:
https://github.com/tchoulihan/torrenttunes-client#command-line-client
