### ISSUE TITLE
Project language should be set to Java

### ISSUE THREAD

**Issue by iadj** [tchoulihan/torrenttunes-client#45]
Loving this project, but I believe it's mainly written in Java. It's currently categorized under 'Javascript'.

**Comment by tchoulihan** [comment]
I just spent a few minutes on this and couldn't figure it out. Its nothing that I can control really, its a github library that automatically scans your project called https://github.com/github/linguist . I tried to figure out how to get it to ignore certain folders using a .gitattribute file, but nothing worked. 

I'll close this unless you'd like to submit a pull request. The folder that should be ignored is `src/main/resources/web/bower_components/`

**Comment by tchoulihan** [comment]
I just got somebody to help me with this, its fixed for real now.

**Comment by iadj** [comment]
Awesome! While we're on the subject: as JS and Node dev I'd love to see a JSON API! This project seems very interesting, and an api to communicate with the server would open up possibilities with all kinds of languages and frameworks.

**Comment by tchoulihan** [comment]
Its a restful web service. I'm about to add a command-line client soon.
