### ISSUE TITLE
Is there a way to create a "installable" file?

### ISSUE THREAD

**Issue by Clarin98** [tchoulihan/torrenttunes-client#46]
Could be interesting if you want to bringing people closer to this project, and to expand the use of app. Also, I suggest you that create a desktop shortcut with this executable, a great way to extend this idea.

**Comment by tchoulihan** [comment]
Both of those are done. The .jar is an installable file that works on OSX, windows, and linux, and makes shortcuts for all three. 

https://github.com/tchoulihan/torrenttunes-launcher/releases/download/1.0.0/torrenttunes-launcher.jar

**Comment by Clarin98** [comment]
Hey, do you have a IRC chat for support or something like that?

**Comment by tchoulihan** [comment]
Talking to me here for support is the best way, what's the issue?

**Comment by Clarin98** [comment]
Well, could be interesting if torrenttunes has a independent GUI, an app like spotify, not in web interface. Thanks.

**Comment by tchoulihan** [comment]
For desktop apps, the web interface is the best way to go for now, unless
someone would like to make one in qt.

Next up on my agenda is an android app though.
