### ISSUE TITLE
use Strike for comprehensive torrent searching

### ISSUE THREAD

**Issue by kxra** [tchoulihan/torrenttunes-client#50]
Hope this is helpful: https://getstrike.net/torrents/

**Comment by tchoulihan** [comment]
If it was, I wouldn't know, because that site is down.

**Comment by kxra** [comment]
oh it likely went down because the Aurous release got a lot of traffic and probably brought down the server they both ran off of. it's up now!

**Comment by tchoulihan** [comment]
Either way, its not really relevant; this service uses normalized individual song torrents that are all mostly not that old, and are already indexed.

**Comment by thekyriarchy** [comment]
here are more details on it, for others who may have ended up here 

https://web.archive.org/web/20160204020104/http://blog.getstrike.net/post/138192622233/were-moving-away-from-torrents-so-whats-next
https://web.archive.org/web/20160204020224/https://github.com/StrikeOrg/strike-search
https://github.com/jakop345/strike-search
