### ISSUE TITLE
No seeders in my shared songs

### ISSUE THREAD

**Issue by modmar** [tchoulihan/torrenttunes-client#53]
I shared the music by command line  however when i search for one of this  songs in torrenttunes i seems like there aren´t seeders... I want to know why.

Moreover i am setting up torrenttunes in a server, torrenttunes-client need X11 running and i don´t like the idea of having it on the server, so should I install torrenttunes-server? or there are another way to run torrenttunes-client without X11?

Sorry for my english and thank you for the help ;)

**Comment by tchoulihan** [comment]
> I shared the music by command line however when i search for one of this songs in torrenttunes i seems like there aren´t seeders... I want to know why.

When you do this, **you** are the seeder for the song. You have to keep that command line client running... its a torrent program that's seeding that song you scanned. The web app doesn't know the number of seeders until someone tries to download that.

> or there are another way to run torrenttunes-client without X11?

Just follow [these instructions](https://github.com/tchoulihan/torrenttunes-client#command-line-client). You don't need to run the torrenttunes-server, just the client. Let me know if you have any questions.

**Comment by modmar** [comment]
I run without X11 running, nohup java -jar torrenttunes-launcher.jar &> log.out &  and then I have the following in the log.out:
> Exception in thread "main" java.awt.HeadlessException:
 No X11 DISPLAY variable was set, but this program performed an operation which requires it.
        at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
        at java.awt.Window.<init>(Window.java:536)
        at java.awt.Frame.<init>(Frame.java:420)
        at javax.swing.JFrame.<init>(JFrame.java:233)
        at com.torrenttunes.launcher.tools.SwingConsoleWindow.createAndShowGui(SwingConsoleWindow.java:28)
        at com.torrenttunes.launcher.tools.SwingConsoleWindow.start(SwingConsoleWindow.java:45)
        at com.torrenttunes.launcher.Main.doMain(Main.java:46)
        at com.torrenttunes.launcher.Main.main(Main.java:123)

However, with X11 running  it works. Now i try to share music, okey, no problem, there are an error, but still sharing. When I look in log.out i can see " Is DHT Running? false "  it should be  true no?

Finally I can see the songs in torrenttunes, but there are no seeds...
Ahhh  I don´t  stop it, it is still running...

Ty

**Comment by tchoulihan** [comment]
I still don't understand your problem.

> Finally I can see the songs in torrenttunes, but there are no seeds...

And my quote from above:

> When you do this, **you** are the seeder for the song.
