### ISSUE TITLE
www.torrenttunes.ml should redirect to torrenttunes.ml

### ISSUE THREAD

**Issue by exadeci** [tchoulihan/torrenttunes-client#54]
You shared the address with `www` but when going to this address the webclient stil tries to do a `pushState` on the address `torrenttunes.ml` and it's a security risk so it's blocked
```
Uncaught SecurityError: Failed to execute 'pushState' on 'History': A history state object with URL 'http://torrenttunes.ml/?song=951b2d10-3af1-468e-8a30-ced9ad21f804' cannot be created in a document with origin 'http://www.torrenttunes.ml'.replaceParams @ tools.js:706(anonymous function) @ main.js:951j @ jquery.js:3099k.fireWith @ jquery.js:3211x @ jquery.js:8264(anonymous function) @ jquery.js:8605
tools.js:30 http://178.32.153.126:80/get_torrent_progress/9f8b4178647e17427e641b2260352c89267c25af
```
The easiest might be to redirect with your domain

**Comment by tchoulihan** [comment]
Totally agree, I'll close this out once I finish this.

**Comment by tchoulihan** [comment]
I just fixed this with a commit to the server web version.

All www ones now redirect to the regular `http://torrenttunes.ml` one now.
