### ISSUE TITLE
Font-awesome not working in firefox

### ISSUE THREAD

**Issue by tchoulihan** [tchoulihan/torrenttunes-client#6]
From #3 .

**Comment by Nutomic** [comment]
[Syncthing](https://syncthing.net/) also seems to use font-awesome for the web gui, and it works fine in Firefox. Maybe you can see how it is done there?

**Comment by tchoulihan** [comment]
@Nutomic Unrelated question, but did you just added a bunch of music recently? I tried dling some Jay-Z with multiple clients, and the torrents aren't starting until like 20 minutes later.

**Comment by Nutomic** [comment]
Yeah I did. Could it be because I use a vpn?

**Comment by tchoulihan** [comment]
That's probably it, we should test it. 

I originally started seeding on a VPN, but the connections wouldn't go through very quickly, and the VPN I was using cut my upload speed by a factor of 10. 

Hrm..... I don't want to ask you to stop using a VPN if you're not comfortable though, but I do want the music to be highly available.

Could you do also do some speed tests, while running and not running the vpn? : http://speedof.me/

BTW your collection kicks ass.

**Comment by Nutomic** [comment]
with vpn:
![speedof me_15-09-08](https://cloud.githubusercontent.com/assets/1044450/9745937/0880b42e-5675-11e5-8fa6-38261eb688e5.png)

without vpn:
![speedof me_15-09-08 1](https://cloud.githubusercontent.com/assets/1044450/9745980/399a2720-5675-11e5-829b-96c2eb53b9d7.png)

My wifi is also a bit flaky, so that could have an effect, too. And I live in Germany, there's no chance I can torrent without a vpn.

Thanks, it took a while to get all that :)

**Comment by tchoulihan** [comment]
Hrm.. your upload speed isn't the problem..

But I still get the same issue torrenting from you. Do you have problems with seeding with any other torrent clients?

The possibilities I can think of are:

* Do you have any OS firewalls running?
* Maybe your router has its firewall turned on
* Router blocking ports, or not forwarding traffic to you.
* Does your VPN give you any instructions for how to make it seed with torrents properly?

**Comment by Nutomic** [comment]
I can open the port in my vpn (didn't even know that). What port is it?

Btw, I've currently disabled seeding because it seriously affects performance (I have 80GB of music on a not so fast laptop). Might turn it back on when I go to work.

**Comment by tchoulihan** [comment]
@Nutomic Lets continue this over at #9.
