### ISSUE TITLE
TorrentTunes hasn't been started yet on 64 bit Arch Linux

### ISSUE THREAD

**Issue by BtpPrograms** [tchoulihan/torrenttunes-client#67]
![2016-01-03-175749_470x379_scrot](https://cloud.githubusercontent.com/assets/9993510/12081321/a7501138-b243-11e5-8cba-3d8299378562.png)

The TorrentTunes website (torrenttunes.ml) works fine directly through my browser. However, when I install the program locally (through the launcher and the manual build instructions) I'm not able to play any music. When I press play they load for a few moments and display the message shown in the picture above. The songs that I tested had 3 to 5 seeders and played immediately when I tried them from the main website. I've attached a log file.

[log.txt](https://github.com/tchoulihan/torrenttunes-client/files/76775/log.txt)

**Comment by BtpPrograms** [comment]
I'm away from home and I found that the network here is blocking bittorrent. I think that may be the cause so I'm going to close this issue for now.

**Comment by tchoulihan** [comment]
Gotcha, let me know if that's the issue.
