### ISSUE TITLE
TorrentTunes Hasn't been started yet... windows10 64bit

### ISSUE THREAD

**Issue by Hyenesheitan** [tchoulihan/torrenttunes-client#68]
Hello
When I want to listen to music, I have an error message

When I click Browser, I have access to the singer / group, but I can not click a singer / group to listen to music.
Windows10 64bit chrome and ie ...
Forgive me for my english

C:\Users\Hyene\Desktop\Torrenttune>java -jar torrenttunes-launcher.jar
15:06:01.766 [main] INFO  com.torrenttunes.client.tools.Tools - Home directory already exists
15:06:01.784 [main] INFO  com.torrenttunes.client.tools.Tools - The source directory already exists
15:06:01.789 [main] INFO  com.torrenttunes.client.tools.Tools - tools.js = C:\Users\Hyene/.torrenttunes-client/src/web/js/tools.js
15:06:01.813 [main] INFO  c.t.client.db.InitializeTables - Using database located at : C:\Users\Hyene/.torrenttunes-client/db/db.sqlite
15:06:01.821 [main] INFO  c.t.client.db.InitializeTables - DB already exists
15:06:02.026 [main] INFO  com.torrenttunes.client.db.Actions - Storage path = C:\Users\Hyene/.torrenttunes-client/music
15:06:02.027 [main] INFO  com.torrenttunes.client.db.Actions - Applying libtorrent Settings...
15:06:02.033 [main] INFO  c.t.client.tools.DataSources - Operating system: windows 10, JVM bits: 32
15:06:02.035 [main] INFO  c.t.client.tools.DataSources - Using libtorrent @ C:\Users\Hyene/.torrenttunes-client/src/lib/x86/jlibtorrent.dll
15:06:02.073 [main] INFO  c.t.client.LibtorrentEngine - Starting up libtorrent with version: 1.1.0.0
15:06:03.370 [main] INFO  c.t.client.LibtorrentEngine - Is DHT Running? false
15:06:03.576 [main] INFO  ROOT - System language = fr or Locale language: fr
15:06:03.578 [main] INFO  com.torrenttunes.client.tools.Tools - Opening web page: file://C:/Users/Hyene/.torrenttunes-client/src/web/html/main_en.html
15:06:03.588 [main] ERROR c.t.client.tools.DesktopApi - Process is running.
15:06:03.592 [main] INFO  c.t.client.LibtorrentEngine - File #0/2 songs in library
15:06:03.628 [main] INFO  c.t.client.LibtorrentEngine - added torrent: 08. Enchanted By The Moon.mp3
path: C:\Users\Hyene\.torrenttunes-client\torrents\6efb5468d4dd4059357ed861eda5f9ae735d4dd9.torrent
info_hash: 6efb5468d4dd4059357ed861eda5f9ae735d4dd9
15:06:03.651 [main] INFO  c.t.client.LibtorrentEngine - File #1/2 songs in library
15:06:03.653 [main] INFO  c.t.client.LibtorrentEngine - added torrent: 09. A New Day.mp3
path: C:\Users\Hyene\.torrenttunes-client\torrents\4827eb90a196531f0f098a6234f0d744f83f50a0.torrent
info_hash: 4827eb90a196531f0f098a6234f0d744f83f50a0
15:06:03.663 [main] INFO  c.t.client.LibtorrentEngine - Done seeding library, total of 2 torrents shared
15:08:06.490 [qtp24660740-15] INFO  c.t.client.webservice.Platform - Powering off...

C:\Users\Hyene\Desktop\Torrenttune>pause
Appuyez sur une touche pour continuer...

**Comment by tchoulihan** [comment]
Lets use this, I prefer github. What browser are you using?

**Comment by Hyenesheitan** [comment]
I use Chrome.
I am testing on IE and Chrome on two Windows10.

Thank you for answering.

**Comment by tchoulihan** [comment]
> The demo runs on 2 PC.

What do you mean by this?

The internal IP port it uses is `4568`, so you should be able to access http://localhost:4568/hello after the service is loaded up. Verify this for me in a new browser tab after you've started it up.

From your log, it looks like everything is working fine, except for this line:
`15:08:06.490 [qtp24660740-15] INFO c.t.client.webservice.Platform - Powering off...`

Remember that when you close out that browser window, it stops the java program.

**Comment by Hyenesheitan** [comment]
To http: // localhost: 4568 / I
500 Internal Error
To: "The demo runs on 2 PC."
http://torrenttunes.ml/

**Comment by tchoulihan** [comment]
I'm not really sure how to diagnose this, do you have a weird internal port setup, or routing that may be strange?

Try to kill the java process, then start it again?

**Comment by Hyenesheitan** [comment]
I connected to the neighbor, always the same symptom :'( so not a router port.

I kill java and also reboot the pc same symptom.

**Comment by tchoulihan** [comment]
Hrm, the torrents seem to be downloading fine... I'll look into this further tomorrow.

**Comment by Hyenesheitan** [comment]
I uninstall and reinstall but still the same thing :'(

**Comment by tchoulihan** [comment]
> i also now "java.sql.SQLexception: Incorrect key file for table '/tmp/#sql_243_0.MYI'; try to repair it" 

I fixed this a little bit ago, so many people were using the service that the disk space got full on the web client, so I had to clear the cache. Its functioning now, and I added something to make sure it clears the cache when disk space drops below 100MB.

I just figured out your issue. I remember having to do this for chrome. Here's the answer:

http://stackoverflow.com/a/13262673/1655478

Basically, chrome doesn't want you to be able to access local files without a special flag. There's no way around adding that flag by default, if using chrome. Let me know if you got this working.

**Comment by Hyenesheitan** [comment]
I added "--allow-file-access-from-files" .exe Chrome.
I always error "TorrentTunes beens Has not started yet"
With Internet Explorer, the song list is not displayed at all.

**Comment by tchoulihan** [comment]
Remember that when you close the window, it closes the program. 

Some others have said that you have make sure to close out chrome completely(it might have a background process running).

I tested chrome out on my windows machine with that flag, and it was working fine.

**Comment by Hyenesheitan** [comment]
The message arrives at the opening tune torrent, I do not farm.
But I have the same concern of 2 pc.
I will look on a third.

**Comment by tchoulihan** [comment]
I can tell you how to see the error on chrome, I'm 99% sure of what error you'll see.

Right click anywhere, and click `Inspect`, then click the `console` tab. Tell me any red errors you see.

**Comment by Hyenesheitan** [comment]
I have this
Uncaught SecurityError: Failed to execute 'pushState' on 'History': A history state object with URL 'file:///C:/Users/Hyene/.torrenttunes-client/src/web/html/main_en.html' cannot be created in a document with origin 'null'.

**Comment by tchoulihan** [comment]
Yep, exactly as I thought, and it was the error I was getting before adding the `--allow-file-access-from-files` flag. You didn't add it correctly, or didn't completely close out chrome.

**Comment by Hyenesheitan** [comment]
We must open the cmd and write:
"C:\ProgramFiles(x86)\Google\Chrome\Application\chrome.exe" --allow-file-access-from-files and press Enter.
Chrome it starts, then click on icon TorrentTunes, TorrentTunes opens in the new window of Chrome and function I sound.

Thx.

But this is not permanant and there are security risks :s

**Comment by tchoulihan** [comment]
I'll leave this open, because I may do another workaround in the way this is handled, so this wouldn't be necessary.

**Comment by Hyenesheitan** [comment]
Great, job !!! thx :)

**Comment by tchoulihan** [comment]
No probs, I'll close this out.
