### ISSUE TITLE
Juste a question

### ISSUE THREAD

**Issue by Djang0** [tchoulihan/torrenttunes-client#73]
Hi,

Is it possible to install a web client on raspberry pi 2 ? If someone did would it be possible to have some brief howto?

thanks

**Comment by tchoulihan** [comment]
I don't see why not, except maybe system requirements.

Follow these instructions:
https://github.com/tchoulihan/torrenttunes-client#command-line-client

**Comment by Djang0** [comment]
great ! ... I wonder which arm distrib  of jdk 8 I have to install 32 or 64 bits? I'm using osmc as os ... may be this is not your area of expertise and/or not the right place to ask ...

**Comment by tchoulihan** [comment]
Not my area of expertise, I don't have one. Google how to install java 8 on raspberry pi.

**Comment by itolosa** [comment]
Preferably 64 bits, although 32 may be ok (http://superuser.com/questions/271173/how-important-is-having-64-bit-programs-on-64-bit-os). There are arm binaries for arm x32 and x64 here: http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

**Comment by Djang0** [comment]
Thank you for the help @itolosa. I think got this now...

**Comment by tchoulihan** [comment]
I'll close this issue then, unless you guy's request me to reopen.
