### ISSUE TITLE
making it easy for people to help seed songs.

### ISSUE THREAD

**Issue by NIXOYE** [tchoulihan/torrenttunes-client#81]
how can people interested in torrentunes help seed their favorite songs\albums? also how does one run their own webclient of torrenttunes?

**Comment by tchoulihan** [comment]
Multiple ways, in each song dropdown, there are magnet links. There is also a download album torrent zip button, and a download artist discography torrents link button, which contains a zip file full of .torrents for every song, which you can help seed in your own torrent client if you like.

Other than that, you can just run the client and it will seed automatically for you.

**Comment by tchoulihan** [comment]
Haven't heard anything back on this.
