### ISSUE TITLE
Add a command line option for -noBrowser

### ISSUE THREAD

**Issue by ryanfelder** [tchoulihan/torrenttunes-client#83]
I would like to run TorrentTunes as a service when I log in.

I can run the command line client automatically, but it also opens a browser window (undesired), and if I close that browser window, the torrent tunes client stops (also undesired)

I'd like to be able to run it without it opening a browser window automatically, so that I can visit it as I please. I have set it up the link as a web application so it lives in my dock on linux.

My apologies if this is already possible, I have not found any help reading the webpage or closed tickets.

**Comment by tchoulihan** [comment]
Here's how to run the client as a command line.

https://github.com/tchoulihan/torrenttunes-client#command-line-client

I have the browser window thing default right now, but I can add a command line flag to not open up a browser window if you'd like.

If you want to run it on startup, it depends on the distro, but you'd just add that `java -jar` command to your startup file.

**Comment by ryanfelder** [comment]
Yes please, a flag for no browser window at startup, and also maybe make it
selectable if the torrent tunes client closes when I close the browser
window.

These two would provide a good enough 'daemonize' mode.

Not sure why but the behaviour that causes the client to stop when I close
the browser happens on chromium, but not on another browser, midori.

**Comment by tchoulihan** [comment]
I haven't tested midori, just chrome, firefox, and safari. Midori must not be adhering to some standards that all the other browsers are.

I'll add this as a feature request, and get this done soon.

**Comment by ryanfelder** [comment]
Thank you!

**Comment by tchoulihan** [comment]
If you use the normal shortcut version, or the torrenttunes-launcher.jar, it should update automatically.
