### ISSUE TITLE
Support localizations

### ISSUE THREAD

**Issue by istanbulmeshnet** [tchoulihan/torrenttunes-client#86]
Allow localizations of the interface.

**Comment by tchoulihan** [comment]
Which languages, to be specific? I already have french and spanish. 

Here's an example of the spanish translations file, just let me know what language specifically you want added.

https://github.com/tchoulihan/torrenttunes-client/blob/master/src/main/resources/values/strings_es.json

**Comment by tchoulihan** [comment]
Haven't heard anything on this, I'll open it up again if someone wants to add another specific language.
