### ISSUE TITLE
VPN Seeding issues

### ISSUE THREAD

**Issue by tchoulihan** [tchoulihan/torrenttunes-client#9]

**Comment by tchoulihan** [comment]
Torrenting works over a range of ports, but the ports I have allocated in torrenttunes is 49154-65535 . Try opening up at least port 49154.

Also about performance, you'll have to tell me more about your problems.

My seeding machine is an old ass 1GB ram netbook, on a connection about 5x worse than yours, and its successfully seeding a lot more than 80GB without problems. It only hurts the network when its starting up and has to do the torrent-announces. Afterwards, it should take 0 bandwidth.

Could you try starting torrenttunes again and telling me the results?

**Comment by Nutomic** [comment]
Okay I've opened the port. 

Here's the cpu usage, this is after initialization with no transfers. And it's like that all the time. Maybe has to do with Linux or OpenJDK?
![htop](https://cloud.githubusercontent.com/assets/1044450/9775416/417ed4d8-574f-11e5-9a0c-54d80fee7031.png)

**Comment by tchoulihan** [comment]
Hey its working! I'm able to DL from you fine now with that port open. 

I'm using the regular oracle JDK, which might have a *little* better performance, but I haven't tested it so I can't be sure. I've noticed that when seeding a lot, my CPU and ram usage are also quite high. It hasn't been too much for my little netbook to handle, but Performance improvements should be on my list.

As far as the CPU/RAM usage, let me finish a feature that I'm working on, and I'll do some profiling and add performance issues to my list.

**Comment by tchoulihan** [comment]
I would close this out, but I just tried to dl another song I'm pretty sure you're hosting, and your seed doesn't seem to be available.

**Comment by Nutomic** [comment]
That's because I don't have it running all the time (mostly for performance reasons). So the VPN should be fine.

**Comment by tchoulihan** [comment]
Gotcha, I'll close this out then. I'll have a big performance boost in the next release, turns out I had a logging parameter on that I shouldn't have been using.

https://github.com/tchoulihan/torrenttunes-client/commit/739d70d990eb60ebb63d1d943a423ed979d3c10b

**Comment by tchoulihan** [comment]
Hey @Nutomic , I just did another release, where performance should be improved a lot. Could you help me verify this?

Also, did you upload lauryn hill? I tried to dl it today but it was unavailable.

**Comment by Nutomic** [comment]
My internet is currently dead -.-

Hope they'll get it fixed by tomorrow.

**Comment by tchoulihan** [comment]
No prob good sir. Hang in there.
http://giphy.com/gifs/yjos61Qgsy17q/html5
