### ISSUE TITLE
Torrenttunes begin frozen

### ISSUE THREAD

**Issue by Clarin98** [tchoulihan/torrenttunes-client#97]
I have executed Torrenttunes for 3 times in my pc (Debian 8 sid) and always shows this in terminal:
"[main] INFO  c.t.client.LibtorrentEngine - Done seeding library, total of 0 torrents shared"

Can you help me? :)

**Comment by tchoulihan** [comment]
I just pushed a new release, `0.7.9` try it again. If you're using the `launcher.jar`, just load up the program. Otherwise, download this jar:

wget https://github.com/tchoulihan/torrenttunes-client/releases/download/0.7.9/torrenttunes-client.jar

**Comment by Clarin98** [comment]
Solved, thanks :)
